// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

// AdminUser defines model for AdminUser.
type AdminUser struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"emailVerified"`
	Id            string `json:"id"`
	Name          string `json:"name"`
	Role          string `json:"role"`
}

// AdminUserData defines model for AdminUserData.
type AdminUserData struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"emailVerified"`
	Name          string `json:"name"`
	Role          string `json:"role"`
}
